- p2p/client.go
- p2p/client_test.go
> Use addresses in multiaddr format.

- docs/lazy-adr/adr-001-node-interface.md
> Update lazy ADR 001

- conv/addr.go
- conv/addr_test.go
- conv/errors.go
- node/node.go
- p2p/errors.go
- rpcclient/local.go
This is the easiest, non-obstructive method to enable running cosmos-sdk tests with optimint.
> Bring back address conversion method

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .golangci.yml
- README.md
- node/node.go
- node/node_test.go
- p2p/client_test.go
- p2p/utils_test.go
- rpcclient/local_test.go
* add linting configuration
* fix existing errors
> Enable golangci-lint GitHub action

- .github/workflows/test.yml
This change is extracted from #53 - it enables go build/test workflow on all PRs.
> Enable test workflow on all PRs

- README.md
I clicked on the green button on #102 a bit to fast :facepalm:  This PR corrects the link.
> Add valid linkt to Twitter badge

- block/manager.go
- conv/abci/block.go
- node/integration_test.go
- state/executor.go
- state/executor_test.go
> Set ChainID in ABCI Header

- state/executor.go
> Actually fix a ChainID issue

- .github/workflows/test.yml
- go.mod
- go.sum
> chore: update to go1.17

- CHANGELOG-PENDING.md
- go.mod
- node/node.go
- rpc/client/client.go
- rpc/json/service_test.go
- state/indexer/block.go
- state/indexer/block/kv/kv.go
- state/indexer/block/kv/kv_test.go
- state/indexer/block/kv/util.go
- state/indexer/block/null/null.go
- state/indexer/query_range.go
- state/txindex/indexer.go
- state/txindex/indexer_service.go
- state/txindex/indexer_service_test.go
- state/txindex/kv/kv.go
- state/txindex/kv/kv_bench_test.go
- state/txindex/kv/kv_test.go
- state/txindex/kv/utils.go
- state/txindex/kv/utils_test.go
- state/txindex/null/null.go
> Block and Tx indexing backend for optimint

- CHANGELOG-PENDING.md
- rpc/client/client.go
- rpc/client/client_test.go
> feat: Implement NumUnconfirmedTxs RPC call

- node/node.go
I was getting a `ineffective break statement. Did you mean to break out of the outer loop? (SA4011)`, and realized this break statement doesn't actually do anything (since it breaks out of the switch instead of the loop).
https://github.com/celestiaorg/optimint/blob/5bdc6d3b886871782c57a2906b1986d9958d13f7/node/node.go#L170
Fix to break out of the loop when the channel is done.
Surprised this infinite loop wasn't tested for?
> Break out of loop instead of doing nothing

- state/indexer/block/kv/kv.go
- state/txindex/kv/kv.go
> Fix ineffective breaks

- CHANGELOG-PENDING.md
- rpc/client/client.go
- store/store.go
- store/store_test.go
- store/types.go
* support saving and loading ABCIResponses in Store
* impelement BlockResults RPC
Resolves #235
> feat: implement BlockResults RPC function

- CHANGELOG-PENDING.md
- store/badger.go
> fix: use KeyCopy instead of Key in BadgerIterator

- CHANGELOG-PENDING.md
- rpc/client/client.go
- rpc/client/client_test.go
> feat: ConsensusState/DumpConsensusState implementation

- CHANGELOG-PENDING.md
- go.mod
- rpc/client/client.go
- rpc/client/client_test.go
- types/tx.go
Implements the Tx method as required in issue [238](https://github.com/celestiaorg/optimint/issues/238)
> Tx Method implementation

- CHANGELOG-PENDING.md
- block/manager.go
- rpc/client/client.go
- rpc/client/client_test.go
- state/executor.go
- state/executor_test.go
- store/store.go
- store/types.go
This is a draft of new approach to Validator Set handling. Reusing code for full compatibility.
> Minimalistic validator set handling

- CHANGELOG-PENDING.md
- rpc/client/client.go
> feat: minimal implementation of ConsensusParams method

- CHANGELOG-PENDING.md
- node/node.go
- rpc/client/client.go
- rpc/client/client_test.go
Implements the GenesisChunked from issue #232
> Implement GenesisChunked method

- CHANGELOG-PENDING.md
- conv/abci/block.go
> fix: map LastBlockID.Hash to LastHeaderHash in conversion

- CHANGELOG-PENDING.md
- CHANGELOG.md
PRs list generated with:
```
gh pr list -s merged -L 200 --json number,title,author -t '{{range .}}- {{.title}} ([#{{.number}}](https://github.com/celestiaorg/optimint/pull/{{.number}})) [@{{.author.login}}](https://github.com/{{.author.login}}/)
{{end}}'
```
and later manually split into sections and cleaned up a bit.
> docs: add release v0.1.0 to CHANGELOG.md

- CHANGELOG-PENDING.md
- rpc/client/client_test.go
Previous builds shows that after first fix, another problems showed up:
https://github.com/celestiaorg/optimint/runs/5456624398?check_suite_focus=true
Resolves #293 (again :joy:)
> fix: make `TestValidatorSetHandling` even more stable

- CHANGELOG-PENDING.md
- rpc/client/client.go
- rpc/json/handler.go
Fixes https://github.com/celestiaorg/ethermint/issues/9
> Add ProposerAddress as ValidatorInfo.Adress in Status rpc

- CHANGELOG-PENDING.md
- CONTRIBUTING.md
- README.md
Adds a basic contribution guide :)
Resolves issue https://github.com/celestiaorg/optimint/issues/140
> Adds a contribution guide

- .github/workflows/build-evmos.yml
Replaces: https://github.com/celestiaorg/optimint/pull/331 and adds multi platform (amd64 and arm64) builds
Resolves: https://github.com/celestiaorg/optimint/issues/328
> multi platform evmos builds w/ ethermint v0.11.0+0.1.0

- block/manager.go
This is a temporary solution that ensures that we're not proceeding with block production, if we're not able to publish blocks to DA.
It will be refactored soon (right after release).
> feat: retry DA submission

- da/celestia/celestia.go
- da/celestia/mock/server.go
> fix: handle application level errors in celestia-node API

- types/serialization.go
- types/serialization_test.go
It's expected to fail a unit test. Fix will be submitted in next commit.
Resolves: https://github.com/celestiaorg/optimint/issues/446
> tests: issue with ConsensusParams deserialization

- .github/workflows/docker-build-test-ethermint.yml
This fixes ethermint docker CI actions.
> Change rollmint ethermint to optimint

- .github/dependabot.yml
dependabot configuration is outdated. Entire team should participate in those reviews.
Resolves #598.
> ci: dependabot: request review from GH team

- README.md
This PR removes the outtdated design document link.
> remove design doc

- block/manager.go
- da/mock/mock.go
> fix: call `Header.Height` as function in logger

- NOTICE
This change is coming from an offline conversation. Owner needs to be the legal entity and updating from specific date range to open ended.
> NOTICE: update timeline and owner for copyright

- node/header_exchange.go
fixes https://github.com/rollkit/rollkit/issues/749
> enabling syncer for aggregator nodes

- block/manager.go
- node/full_client_test.go
- state/executor.go
fixes https://github.com/rollkit/rollkit/issues/819 and https://github.com/rollkit/rollkit/issues/816
> Support multi sequencer

- node/full_client_test.go
- node/full_node_integration_test.go
- state/executor.go
> header: verify aggregator hash against validators

- block/manager.go
- node/full_client_test.go
- state/executor.go
- store/store.go
- types/validation.go
> Support based rollups + centralized sequencer to based rollup integration test

- block/manager.go
- da/celestia/celestia.go
- da/da.go
> handle error correctly when checking for data at a height that does not exists

- .yamllint.yml
- Makefile
Adds option for:
- Cleaning testing cache
- test both race and without race
- lint
Adds `--count=1` flag for tests to avoid cached results
> feat: Improvements to Makefile

- node/full_client_test.go
> Fix race condition in TestValidatorSetHandling 

- go.mod
- go.sum
> upgrade go-header to 0.2.8 which fixes the no peers found error

- Makefile
- README.md
Added a section to the README to make it more explicit as to which versions rollkit is compatible with with celestia and how to use the local devnet vs arabica and mocha.
> README: add section with clearer compatibility and development steps

- README.md
> adding a table to README showing rollkit compatibility

- README.md
> update readme with latest release information

- node/full_node_integration_test.go
> code-hygiene: Fix use of subtests in node integration tests

- block/manager.go
- block/manager_test.go
- da/test/da_test.go
- node/full_client_test.go
- node/full_node_integration_test.go
- node/full_node_test.go
- node/helpers_test.go
- state/txindex/kv/kv_test.go
- store/prefix_test.go
- store/store_test.go
> code-hygiene: Clean up node shutdown in testing

- proto/get_deps.sh
> fix CM_VERSION in proto/get_deps.sh

- .golangci.yml
- node/block_exchange.go
- node/full_client.go
- node/header_exchange.go
- node/light_client.go
- node/test_helpers.go
- rpc/json/test_helpers.go
- types/test_utils.go
Duplicate imports when given custom names were not being caught by the linter. This PR adds the needed flag and fixes some errors.
> golangci: add import duplication flag

- go.mod
- go.sum
> feat: bump celestia-openrpc

- mempool/clist/clist.go
- node/mempool.go
ref https://github.com/rollkit/rollkit/issues/1125
remove usage of cmsync in rollkit
> remove cmsync usage

- block/manager.go
- config/defaults.go
- da/test/da_test.go
> Switch DABlockTime to 15 seconds

- block/manager.go
- state/executor.go
- state/executor_test.go
- types/block.go
- types/hashing.go
> Add Data Hash Validation to Block's `ValidateBasic`

- .github/workflows/housekeeping.yml
> .github: add ready_for_review trigger for housekeeping workflow

- block/block_exchange.go
- block/exchange.go
- block/header_exchange.go
- node/full.go
- node/full_node_integration_test.go
- node/light.go
- node/test_helpers.go
> Move block/header exchange to block package

- block/manager.go
- block/manager_test.go
- node/full.go
- node/full_client.go
- node/full_node_integration_test.go
> Refactor full node constructor

- README.md
This PR edits the README.md in rollkit/rollkit to allow it to be adapted directly into the documentation site.
This:
Example without hard break:
Example with hard break:
p.s. dang my fork is still rollmint, good times
> chore: update readme for use in rollkit docs in place of "building-with-rollkit" page

- specs/template.md
> (chore): changes to the template for more guidance

- da/grpc/grpc.go
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
- node/full_client_test.go
> Fix mempool batching for v0.11.x

- block/manager.go
- node/full_client.go
- state/executor.go
- state/executor_test.go
- state/indexer_utils.go
- types/params.go
- types/params_test.go
- types/serialization.go
- types/serialization_test.go
Closes: #325
Reference to corresponding [cometBFT code](https://github.com/cometbft/cometbft/blob/6c1deb50b146bf8d27a65fbce8dbba89052dd607/internal/state/execution.go#L615).
Removes validator updates code as well that is now unnecessary due to switch to single sequencer.
> Add ConsensusParams updates handling logic

- go.mod
- go.sum
> chore: bump dep version for multiaddr

- block/manager.go
> Add a default erroring case on unknown enums in DA

- block/manager.go
> Check for closure of txAvailable channel

- go.mod
Closes #1562 
Retract accidental version publish.
> fix: retract v0.12.0 due to accidental publish

- README.md
This updates the README to be more aligned with how the docs are structured. 
It removes all the Celestia specific information and the compatibility table.
> chore: clean up our README to be less Celestia centric.

- block/manager.go
> refactor: Log tx count in DA submission

- block/manager_test.go
- cmd/rollkit/docs/rollkit_start.md
- config/config.go
- da/da.go
- da/da_test.go
- node/full.go
- node/full_node_integration_test.go
- node/full_node_test.go
- node/helpers_test.go
> feat: add support for DA submission options

- cmd/rollkit/commands/run_node_test.go
- node/execution_test.go
- node/helpers_test.go
- node/node_integration_test.go
- node/node_test.go
We had some zombie mock sequencers
> fix: some integration tests

- core/da/dummy.go
> chore: add timestamps to dummy da

- buf.yaml
- proto/rollkit/rollkit.proto
- proto/rollkit/state.proto
> chore: buf linting fixes 

- block/manager.go
- types/signed_header.go
This caused stalling around block 102/103.
Also fixed a crash.
> fix: fix go-header verification errors

- block/rollkit-minimal-header.md
> docs: Minimal Rollkit Header ADR

- block/manager.go
- store/store.go
- store/store_test.go
- store/types.go
- test/mocks/Store.go
This pr removes some extra values from store and removes the responses from executing a block as this would be stored in the execution side
> chore: cleanup state

- block/manager_test.go
- types/pb/rollkit/v1/rollkit.pb.go
- types/serialization.go
Replaces raw public key handling with `crypto` library methods for better clarity and reliability. Updates protobuf imports from `cosmos/gogoproto` to `gogo/protobuf` for consistency. Additionally, improves comments in generated protobuf code for better readability.
> fix: refactor public key handling and regenerate protobuf

- specs/lazy-adr/adr-017-rpc.md
this pr adds a short ADR for RPC in rollkit
> docs: add simple ADR for rpc

- core/sequencer/sequencing.go
- types/utils.go
closes #2127 
this pr merges the sequencer interfaces to reduce complexity
> chore: merge interfaces

- block/manager.go
This ensures that the block includes the public key and address of the signer, improving clarity and accountability in proposer information. The change enhances the block structure for better validation and traceability.
> fix: fill Signer field during block creation

- pkg/cmd/run_node.go
- pkg/cmd/run_node_test.go
- rollups/testapp/cmd/run.go
- rollups/testapp/kv/test_utils.go
- rollups/testapp/main.go
This pr removes new run cmd as it causes issues in the updated design
> fix: fix start command generation

- block/manager.go
- block/manager_test.go
Genesis header can (and should!) be signed in aggregator node. Other nodes are not able to do it, so initially they should just use unsigned one.
> fix: sign genesis header

- specs/lazy-adr/adr-018-forced-inclusion-mechanism.md
> docs: Create Forced Inclusion Mechanism ADR

- .github/ISSUE_TEMPLATE/Epic.yml
- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
> chore: add issue templates

- block/manager_test.go
Adds tests for execValidate that's added in https://github.com/rollkit/rollkit/pull/2237
> test: Add exec validate tests

- .github/workflows/rust-publish.yml
- Cargo.lock
- client/crates/rollkit-client/Cargo.toml
- client/crates/rollkit-types/Cargo.toml
add version to cargo.toml instead of only path since cargo strips the path
> chore: rust cargo fix 

- .github/workflows/rust-publish.yml
this should fix the deployment since packaging wasnt working since there is nothing on crates yet.
> fix: avoid packaging client and types together 

- test/e2e/evm_test_common.go
Starting from Go 1.21, the standard library includes built-in max/min functions.
> refactor: use the built-in max/min to simplify the code

- .github/workflows/test.yml
- apps/evm/single/docker-compose.yml
- block/aggregation.go
- block/aggregation_test.go
- block/reaper.go
- docs/adr/adr-021-lazy-aggregation.md
- execution/evm/docker/docker-compose-full-node.yml
- execution/evm/docker/docker-compose.yml
- node/full.go
- node/light.go
- pkg/cmd/run_node.go
- scripts/README-EVM.md
- scripts/run-evm-nodes.go
- scripts/test.mk
- test/docker-e2e/docker_test.go
This PR completes the migration from Rollkit branding to the new ev-node/ev-reth ecosystem. This includes updating all Docker images, service names, environment variables, and documentation references to align with the new branding strategy.
- **Image Updates**: Migrated from `ghcr.io/evstack/lumen:latest` to `ghcr.io/evstack/ev-reth:latest`
- **Service Renaming**: 
- `rollkit-reth` → `ev-reth`
- `rollkit-evm-single` → `ev-node-evm-single`
- `rollkit-reth-full-node` → `ev-reth-full-node`
- **Network Updates**: `rollkit-network` → `evolve-network`
- **Container Names**: Updated all container references to use `ev-reth` naming convention
- **Environment Variables**: 
- `ROLLKIT_IMAGE_REPO` → `EV_NODE_IMAGE_REPO`
- `ROLLKIT_IMAGE_TAG` → `EV_NODE_IMAGE_TAG`
- **CLI Flags**: `--rollkit.enable` …
> chore: Migrate files to ev-reth

- docs/guides/quick-start.md
> fix: domain quickstart

- block/sync_test.go
- pkg/store/store_test.go
Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
> refactor: use a more modern writing style

- apps/grpc/single/docker-compose.yml
- docs/guides/create-genesis.md
- docs/guides/full-node.md
Minor update: the chain-id start param was removed.
> chore: Remove chain-id start flag

- test/docker-e2e/docker_test.go
> chore: bump docker tests to v24 of node

- test/docker-e2e/docker_test.go
> chore: bump da node to 25.2

- test/docker-e2e/docker_test.go
> chore: node update

- apps/evm/single/cmd/rollback.go
- apps/evm/single/go.mod
- apps/testapp/main.go
ref: https://github.com/evstack/ev-node/issues/2590
Wire rollback command to evm simple, align testapp command.
> feat(apps): wire rollback command to evm simple, align testapp command

- pkg/config/config.go
- **File:** `pkg/config/config.go`
- **Line:** 166
- **Change:** Corrected `submittions` to `submissions`
> Fix typo in DAConfig comment

- block/internal/syncing/da_retriever_test.go
- block/internal/syncing/p2p_handler_test.go
- block/internal/syncing/syncer_logic_test.go
Followed the structure of existing tests in the other packages to add test coverage for the p2p handler
> chore: adding p2p handler tests

- block/internal/syncing/syncer.go
Catched by @alpe, events are being dropped, we should just skip bumping the height and retry next time.
> fix(syncer): skip bumping height when event dropped

- block/components_test.go
- block/internal/common/errors.go
- block/internal/executing/executor.go
- block/internal/executing/executor_restart_test.go
- block/internal/executing/executor_test.go
- block/internal/reaping/reaper_test.go
> fix(block): save created block for recovery and simplify genesis flow

- block/internal/cache/manager.go
- block/internal/cache/manager_test.go
- block/internal/executing/executor.go
- block/internal/syncing/da_retriever.go
- block/internal/syncing/da_retriever_test.go
- block/internal/syncing/p2p_handler.go
- block/internal/syncing/p2p_handler_test.go
- block/internal/syncing/syncer.go
- block/internal/syncing/syncer_logic_test.go
- Fix setting header da inclusion at the correct place (after header validation)
- Simplify cache by deleting SetHeader and SetData, as we sync sequentially, so we can always take the next event
- other code cleanup
> refactor(syncing)!: simplify cache and syncing logic

- apps/evm/single/go.mod
- apps/evm/single/go.sum
- apps/grpc/single/go.mod
- apps/grpc/single/go.sum
- apps/testapp/go.mod
- apps/testapp/go.sum
- da/go.mod
- da/go.sum
- execution/evm/go.mod
- execution/evm/go.sum
- execution/grpc/go.mod
- execution/grpc/go.sum
- go.mod
- go.sum
- sequencers/single/go.mod
- sequencers/single/go.sum
- test/e2e/go.mod
- test/e2e/go.sum
Follow-up of https://github.com/evstack/ev-node/pull/2683
> build(deps): bump to core v1.0.0-beta.3

- block/internal/submitting/submitter_test.go
The new version of Go  (after Go 1.22) has been optimized, and variables do not need to be reassigned.
Our project use Go 1.24:
```shell
Directory: apps/evm/single, Go version: 1.24.6
Directory: apps/grpc/single, Go version: 1.24.6
Directory: apps/testapp, Go version: 1.24.6
Directory: core, Go version: 1.24.1
Directory: da, Go version: 1.24.1
Directory: execution/evm, Go version: 1.24.6
Directory: execution/evm/test, Go version: 1.24.6
Directory: execution/grpc, Go version: 1.24.2
Directory: sequencers/single, Go version: 1.24.2
Directory: test/docker-e2e, Go version: 1.24.6
Directory: test/e2e, Go version: 1.24.6
```
For more info: https://tip.golang.org/wiki/LoopvarExperiment#does-this-mean-i-dont-have-to-write-x--x-in-my-loops-anymore
> test: omit unnecessary reassignment

- docs/adr/adr-017-node-pruning.md
- docs/guides/da/celestia-da.md
- docs/guides/da/local-da.md
- docs/guides/da/visualizer.md
- docs/guides/execution/cosmwasm.md
- docs/guides/gm-world.md
- docs/learn/config.md
- docs/learn/data-availability.md
- docs/learn/sequencing/single.md
- docs/learn/specs/block-manager.md
- node/full_node.md
> chore: fix more links

- block/internal/syncing/da_retriever.go
- block/internal/syncing/da_retriever_test.go
- block/internal/syncing/syncer.go
Noticed when trying to sync from da using a wrong working endpoint.
Not all errors were handled.
> fix(syncing): handle incorrect da response
