evstack/ev-node

go.mod, p2p/client.go, p2p/client_test.go, p2p/utils_test.go
Refactoring of P2P layer tests.
Resolves #26, #27.
=> Refactoring of P2P unit tests

docs/lazy-adr/adr-004-core-types.md, docs/lazy-adr/adr-template.md, types/block.go, types/evidence.go, types/tx.go
This PR defines the core data types of an optimint blockchain. We do not seem to have an issue for this change but the rationale is that we need to define these to actually aggregate Transactions into blocks which then get submitted to LazyLedger / the DA layer.
For this to be complete the following items need to be addressed too:
- methods on core types (e.g. for hashing and basic validation etc) and proper documentation comments
- equivalent types for serialization puposes (probably protobuf)
- conversion from and to protobuf
The first is needed to actually use the internal types correctly. The latter two are necessary for transferring core objects over the wire and back.
=> Add core types

da/lazyledger/encoding.go, da/lazyledger/lazyledger.go, da/lazyledger/lazyledger_test.go, go.mod, go.sum
This PR uses signed `sdk.Transaction`s instead of messages. It also uses the port 9090 to broadcast that tx via grpc. Before this PR can be reviewed, it still needs a bit of polish, along with the ability to look up the sequence and account numbers for the account submitting the `WirePayForMsg`.
closes: #60
=> Submit signed transactions instead of messages

node/node.go
Fix some typos found in goreportcard.
=> Fix typos in node/node.go

node/aggregator_test.go, node/node.go, node/node_test.go, p2p/client.go, p2p/client_test.go, p2p/gossip.go
Rationale: this changes are extracted from #92. I made them, because gossiping is generic and I don't want to duplicate code for Txs, Blocks, Proofs, etc. Moreover, I think this abstraction is a good starting point for #93 - validator function could be added to `Gossip` struct.
=> Extract gossiping logic into a type

node/aggregator.go, node/integration_test.go, node/node.go, p2p/client.go, p2p/gossip.go, p2p/utils_test.go, state/executor.go, types/block.go, types/serialization.go
This PR is limited to actual propagation (gossiping) of block headers and includes DALC client query for a block body.
Actual block processing and block synchronization will be addressed in follow-up PRs.
This PR takes changes from #97 a bit further. I introduced `GossipValidator` type to hide libp2p implementation details and clearly separate p2p layer.
=> Block Propagation

state/indexer/block/kv/kv.go, state/txindex/kv/kv.go
For some reason _these were not caught_ by `staticcheck`. I manually noticed there were still `break`s inside of `select`s.
=> Fix missed breaks in selects

CHANGELOG-PENDING.md, go.mod, node/node.go, state/indexer/block/kv/kv.go, state/indexer/block/kv/kv_test.go, state/txindex/indexer_service_test.go, state/txindex/kv/kv.go, state/txindex/kv/kv_bench_test.go, state/txindex/kv/kv_test.go, store/badger.go, store/kv.go, store/prefix.go
* added prefix iterator support to `store`
* replaced tm-db dependency with `store` package in indexer
* bonus: indexer now use the same KV store instance as rest of optimint
Resolves #269
=> Replace tm-db dependency with store package

CHANGELOG-PENDING.md, rpc/json/handler.go, rpc/json/service.go, rpc/json/service_test.go, rpc/json/types.go, rpc/json/ws.go, rpc/json/ws_test.go
RPC: subscription methods
Resolves: #244
Required by: #188
=> RPC: subscription methods

CHANGELOG-PENDING.md, conv/abci/block.go, rpc/client/client.go, rpc/client/client_test.go
This PR adds `BlockChainInfo` method for compatibility with Tendermint RPC
Implements #233
=> Implement BlockChainInfo RPC method

CHANGELOG-PENDING.md, block/manager.go, state/executor.go, state/executor_test.go
Resolves https://github.com/celestiaorg/optimint/issues/284.
I wanted to avoid introducing store to executor, so the responses are returned and saved in `BlockManager`.
=> fix: do save ABCI responses for blocks

CHANGELOG-PENDING.md, rpc/client/client_test.go
Instead of `time.Sleep` a channel is used for reliable synchronization
Resolves #293
=> fix: make `TestValidatorSetHandling` stable

CHANGELOG-PENDING.md, CHANGELOG.md
I'm wrapping up changes, so we have tagged release with proper gRPC version.
=> docs: prepare v0.1.1 release

block/manager.go, config/config.go, da/da.go, da/grpc/grpc.go, da/grpc/mockserv/cmd/main.go, da/grpc/mockserv/mockserv.go, da/mock/mock.go, da/test/da_test.go, log/test/loggers.go, node/integration_test.go, p2p/client_test.go, proto/dalc/dalc.proto, state/state.go, store/store.go, types/pb/dalc/dalc.pb.go, types/pb/optimint/optimint.pb.go
This PR introduces new DALC API into optimint.
Most important changes:
* BlockManager needs to keep track of DA layer height
* single DA layer block can contain multiple Optimint blocks
* sync is now more complicated - but I tried to keep it as simple as possible
Actually, there's no need to explicitly map DA layer height to Optimint height. 
Resolves #281.
=> New DALC API

.github/workflows/lint.yml, .markdownlint.yaml, CHANGELOG.md, docs/lazy-adr/adr-001-node-interface.md, docs/lazy-adr/adr-002-mempool.md, docs/lazy-adr/adr-003-peer-discovery.md, docs/lazy-adr/adr-004-core-types.md, docs/lazy-adr/adr-005-serialization.md, docs/lazy-adr/adr-006-da-interface.md
Markdown linter configured to:
- allow arbitrary line lengths
- allow multiple same headers, as long as they are in different nesting (they are not siblings) - this is required for subsections in CHANGELOG.md
Additionally, `markdownlint -fix` was applied to clean up the files.
=> ci: add markdown linter

.github/workflows/build-evmos.yml
=> fix: execute evmos build only once per PR

block/manager.go, state/state.go
Previously, latest processed DA block height was saved, and as a result syncing couldn't restart.
Resolves https://github.com/celestiaorg/optimint/issues/376
=> fix: keep track of DA height of latest applied block

block/manager.go, da/celestia/celestia.go
* more detailed application level error information
* exponential backoff for block submission
* simple "times 2" strategy with upper limit
* max backoff timeout is equal to block time
* increased number of retries to 30
Resolves #423
Resolves #426
=> feat: improved block submission error handling

rpc/json/handler.go, rpc/json/service_test.go, rpc/json/types.go
Because Tendermint encodes ints as strings, and expects strings while
decoding, Optimint has to encode int values as strings as well.
This PR ensures that Tendermint JSON library is used for encoding of results both in plain HTTP requests and JSON RPC requests.
Resolves #463.
=> Ensure JSON serialization compatibility

block/manager.go
Would resolve #462 . Is there any concerns about this change? The handling may change when #457 is investigated anyways
=> fix: saving block height after committing validators to db

.golangci.yml
Remove duplicate linters and alphabetize list to make it easier to identify duplicates in the future
=> ci: remove duplicate linters

node/node.go, rpc/client/client.go
Resolves #470 (I think?) 
Should the error handling from `initGenesisChunks` be kept inside `GetGenesisChunks`, or be passed to `GenesisChunked` ?
=> chore: move initGenesisChunks call into GetGenesisChunks

block/manager.go, node/node.go, p2p/client.go
This PR introduces `Commit` gossiping logic. Only the latest commit is interesting for full nodes (as older ones are available in DA).
Work will be continued in future PRs.
Resolves #479.
=> feat: support Commit gossiping on P2P level

block/manager_test.go, da/celestia/celestia.go, da/celestia/mock/server.go, da/da.go, da/grpc/grpc.go, da/grpc/mockserv/mockserv.go, da/mock/mock.go, da/test/da_test.go, node/integration_test.go, node/node.go
NamespaceID is removed from Celestia DA configuration. Instead, it's added to DA interface. Mocks simply ignore this. 
Resolves #425.
=> feat: pass namespace ID to DA layers

rpc/client/client_test.go
This test can be enabled as mempool is updated.
=> test: enable TestUnconfirmedTxsLimit

node/integration_test.go
Using cancelable context in integration tests allows proper shutdown of nodes. 
Resolves #531.
=> Use context in integration test

proto/get_deps.sh, proto/tendermint/abci/types.proto
During latest Cosmos SDK v0.46.1 update, I forgot to update proto files and script to get them. This PR fixes this.
=> fix: update proto files to v0.34.21

da/grpc/mockserv/cmd/main.go, da/grpc/mockserv/mockserv.go, da/test/da_test.go
=> pass logger config to mockserver

block/manager_test.go, config/config.go, config/config_test.go, config/defaults.go, da/celestia/celestia.go, da/da.go, da/grpc/grpc.go, da/mock/mock.go, da/test/da_test.go, docs/lazy-adr/adr-004-core-types.md, node/integration_test.go, state/executor.go, types/block.go, types/serialization_test.go
I think naming the new type NamespaceID is straightforward and requires no further explanation.
Let me know if I missed something - the go compiler likes it just fine
=> replaced [8]byte with types.NamespaceID

.golangci.yml, config/config.go, config/config_test.go, conv/config_test.go, da/grpc/mockserv/cmd/main.go, da/test/da_test.go, rpc/json/handler.go, store/store_test.go
=> Configure local-prefix for goimports linter

.github/workflows/docker-build-test-ethermint.yml
Ethermint currently imports optimint, so this replace is replacing an unused module currently, testing in rollmint that ethermint works with a specific optimint version.
Update the edit so build tests what it should.
=> Update build to replace correct module

config/defaults.go, p2p/client.go, rpc/client/client.go, rpc/client/client_test.go
Fill in all the missing fields of Status() rpc for compatibility with Tendermint RPC.
Fixes https://github.com/celestiaorg/rollmint/issues/241
=> fill in all the missing fields of status rpc

block/manager.go, config/config.go, config/config_test.go, config/defaults.go, node/integration_test.go, state/executor.go, state/executor_test.go
Fixes https://github.com/celestiaorg/rollmint/issues/619 by adding a flag to enable fraud proofs. Note that, there is a change in the default behavior after this commit is merged, where previously by default the fraud proofs were enabled, but now they will be disabled and the flag `--rollmint.experimental_insecure_fraud_proofs` must be passed enable fraud proofs.
=> add flag to enable fraud proofs

block/manager.go, node/integration_test.go
The discrepancy stems from how an `Aggregator` and `Full Node` call `SaveNode`. Before, the `Aggregator` did not `SaveNode` after calling `ApplyBlock`. Since `ApplyBlock` modifies the `ISR` list in the block data, we need to call `SaveNode` again.
Also, resolves a issue with passing `isMalicious` boolean correctly in the integration test when creating and starting nodes.
Closes: #566
=> Resolve discrepancy between Aggregator and Full Nodes in Integration Test

block/manager.go
Fix uninitialized commit issue during SaveBlock in publishBlock
=> Fix commit nil issue

da/celestia/celestia.go, go.mod, go.sum
=> feat: celestia DA: support fees

config/p2p.go, node/node.go, p2p/client.go, p2p/client_test.go, p2p/utils_test.go
Resolves https://github.com/celestiaorg/rollmint/issues/386
Blacklists/whitelists are only applied while starting the `Client`, and do not update while the `Client` is running.
=> feat: add ConnectionGater

.github/workflows/lint.yml, .github/workflows/test.yml, block/manager.go, conv/abci/block.go, da/mock/mock.go, da/test/da_test.go, go.mod, go.sum, rpc/client/client.go, rpc/client/client_test.go, rpc/json/service.go, state/executor.go, state/executor_test.go, store/store.go, store/store_test.go, store/types.go, types/block.go, types/hashing.go, types/header.go, types/serialization.go, types/serialization_test.go, types/validation.go
=> Integration with go-header

README.md
Just noticed, that Go version mentioned in readme is old and has to be updated.
=> Update required go vesion in readme

block/manager.go, node/full_client_test.go
Implements the wait time as required in issue #195 and issue #196
=> update wait time

block/manager.go, node/full.go, p2p/client.go
Since `SignedHeaders` are gossiped, there is no use for `Commit` gossiping. Entire related logic should be removed from `p2p.Client` and node(s).
Closes: #686
=> Remove Commit gossiping logic from P2P client

node/full.go, node/light.go, node/node.go
Resolves https://github.com/rollkit/rollkit/issues/673.
=> Add fraud proof gossiping logic to light clients

da/registry/registry.go, da/registry/registry_test.go
=> feat: add Register function to DA registry

docs/lazy-adr/adr-006-da-interface.md
ADR-006 title had a typo where it was called ADR-005 before. Fixes it.
=> Fix ADR-006 title

node/header_exchange.go, types/block.go, types/signed_header.go
fixes https://github.com/rollkit/rollkit/issues/780
=> change Header gossip to SignedHeader gossip

block/manager.go, node/full.go, node/full_node_integration_test.go, node/header_exchange.go, node/light.go, types/signed_header.go
Fixes https://github.com/rollkit/rollkit/issues/781
=> Remove sequencer gossip

da/celestia/celestia.go, da/celestia/mock/server.go, go.mod, go.sum
DA block submission was broken as from go-cnc v0.3.0 we need to change to "PFB" instead of "PFD"
=> update rollkit to use go-cnc v0.3.0

p2p/utils_test.go
The `require.NotEmpty` utility reads through the struct fields of the Host via reflection, while the internal background routine in the host also accesses its field, causing race conditions. The fix is to use `require.NotNil` as it only checks whether the Host is nil or not without accessing its internal fields
=> fix(p2p): fix race condition caused by startTestNetwork

go.mod, go.sum, node/header_exchange.go, types/header.go, types/signed_header.go
Depends on #799 
Unifies `VerifyAdjacent` and `VerifyNonAdjacent` into `Verify`
=> deps: bump go-header

types/validation.go
When validating the Signed Header in Validate Basic we should check if the aggregator hash corresponds to the hash of the validator set.
Closes: #820
=> Validate Aggregator hash from the validator set 

da/test/da_test.go, libs/testfactory/txs.go, p2p/client.go, p2p/gossip.go
Resolves #911, resolves #919, resolves #910
=> fix: Disable CI/CD linter check with rand library, fix server overlap, and data race issue

rpc/json/ws.go
The websocket JSON RPC server did not support CORS. This PR implements this. Fixes #436 #742
=> ws: support cors

block/manager.go, node/full.go, node/full_node_integration_test.go, node/light.go, node/proof_service_factory.go, p2p/client.go, state/executor.go, types/header.go
Update existing fraud proof processing logic to use ProofService from go-fraud package. Also, removes the old fraud proof gossip logic.
Fixes #895 & #945
=> fraud proof processing using go-fraud package

Makefile, node/light.go, p2p/client.go
=> Remove header gossip from p2p module

node/header_exchange.go
Fixes #846 
As per the discussion in #846, the aggregator node only need to initialize the store with genesis header, after that it only needs to broadcast the header without directly trying to append to store. The append is take care by the broadcast api which along with broadcasting also puts the header in the local append queue which then appends to the local store.
=> fix header exchange init error

.github/workflows/test.yml, Makefile
The Code Coverage action appears to be broken, this is an attempt to fix it.
Fix inspired by https://github.com/celestiaorg/celestia-node/pull/2249/files
=> change test.yml and makefile

.github/workflows/test.yml, go.mod, go.sum
Ever since some recent commits, attempting to run `go mod tidy` on Rollkit would results in the following error:
```
github.com/rollkit/rollkit/block imports
github.com/cometbft/cometbft/abci/types imports
github.com/cometbft/cometbft/crypto/secp256k1 imports
github.com/btcsuite/btcd/btcec/v2/ecdsa tested by
github.com/btcsuite/btcd/btcec/v2/ecdsa.test imports
github.com/btcsuite/btcd/chaincfg/chainhash: ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules:
github.com/btcsuite/btcd v0.22.0-beta (/home/dferrer/go/pkg/mod/github.com/btcsuite/btcd@v0.22.0-beta/chaincfg/chainhash)
github.com/btcsuite/btcd/chaincfg/chainhash v1.0.1 (/home/dferrer/go/pkg/mod/github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.1)
```
This PR fixes the ambiguous import …
=> Fix go.mod

da/celestia/celestia.go, da/celestia/celestia_test.go, da/da.go
We have made a breaking change in node v0.10.0 regarding data requests. https://github.com/celestiaorg/celestia-node/commit/62a0b97997b865efd76a2e8d02af8ee5d2a8e912
Previously, a "data not found" meant both "the node failed to retrieve that data, please retry" as well as "the node retrieved the data successfully, but your namespace is not included in the data". We have split these errors, so now we have an `ErrNamespaceNotFound` which indicates a successful request for empty data.
I have no idea how to test rollkit so would love some help on getting that set up
=> fix: handling ErrNamespaceNotFound for node v0.10.0

block/manager_test.go, config/config.go, config/config_test.go, config/defaults.go, da/celestia/celestia.go, da/celestia/mock/server.go, da/da.go, da/grpc/grpc.go, da/grpc/mockserv/mockserv.go, da/mock/mock.go, da/test/da_test.go, go.mod, go.sum, node/full_client_test.go, node/full_node_integration_test.go, state/executor.go, state/executor_test.go, types/block.go
This PR manually upgrades go-cnc from 0.3.0 to 0.4.1, which has a breaking change of 8 byte namespace to 10 byte. 
I have tested the PR using local-celestia-devnet with app:v1.0.0-rc0 and node:v0.11.0-rc2, which are celestia's arabica testnet configurations.
https://github.com/rollkit/local-celestia-devnet/releases/tag/v0.11.0-rc2
=> Upgrade to go-cnc:v0.4.1, use cnc.Namespace

node/full.go, node/full_node_integration_test.go, node/header_exchange.go
=> Refactor header exchange to accommodate block exchange service

node/block_exchange.go, node/full_client.go, node/full_client_test.go, node/header_exchange.go, p2p/client.go
Node ID is set using local p2p host which does not match with cosmos-sdk node ID, which is set using the p2p key. Hence, changing the ID on the rollkit side to match with cosmos-sdk.
=> set node id using p2p key instead of local host id

block/manager.go, da/celestia/celestia.go, da/celestia/mock/server.go, da/da.go, da/grpc/grpc.go, da/grpc/mockserv/mockserv.go, da/mock/mock.go, da/test/da_test.go, proto/dalc/dalc.proto, types/pb/dalc/dalc.pb.go
Resolves: #1080, #1084 
Adding DA Testing PR WIP: #1086
=> Modify SubmitBlock to SubmitBlocks in DA interace

node/full_client.go
There was a potential deadlock for a channel capacity of zero. This code removes that deadlock and adds a comment explaining the code more. 
Related to #1069
=> node: remove potential deadlock on chan capacity of zero

go.mod, go.sum, state/indexer/block/kv/kv.go, state/indexer/block/kv/util.go, state/indexer/query_range.go, state/txindex/kv/kv.go
=> upgrade cometbft to 0.37.2 and fix int64 to *big.Int issues

da/mock/mock.go, da/mock/util.go, state/txindex/indexer_service.go
I did a quick audit of the code for infinite for loops to catch any remaining places where we might be hanging after a shutdown. 
This PR adds some comments to explain some test helpers and adds two select statements that watch for cancellation of subscriptions to help with a cleaner shutdown. 
closes #1069
=> For loop audit

da/mock/mock.go, da/mock/util.go, go.mod, go.sum
`celestia-openrpc v0.1.2` signature for `NewDataAvailabilityHeader` now returns an error, so this needed to be handled.
`RandEDS` and `RandShares` needed to be updated for the new `Share` type.
=> deps: fix celestia-openrpc v0.1.2 breaking changes

da/celestia/mock/server.go, da/test/da_test.go
This PR uses pkg `httptest` to avoid port conflict when running tests under `da/test` i.e. `TestLifecycle`, `TestRetrieve`.
This allows the tests to pass even if an address is bound to the default port i.e. `127.0.0.1:26658`
=> test: use pkg httptest to avoid port conflict

da/celestia/mock/server.go, da/test/da_test.go
This PR improves upon #1144 by simplifying `mock.Server` to use `httptest` directly, avoiding a duplicate `http.Server`. `Server.Start` doesn't need a listener anymore, and it returns the URL at which the `httptest.Server` is running.
=> test: update mock.Server to use httptest.Server

block/manager.go, config/defaults.go, da/mock/util.go, state/executor.go, state/indexer/query_range.go, types/header.go, types/signed_header_test.go, types/test_utils.go
=> Enable subsecond block times using unix nano for Time in BaseHeader

state/executor.go, types/hashing.go, types/signed_header_test.go
=> Recompute signature in signature header tests to make tests throw the right errors

Makefile
Closes #223 
Instead of adding a formatted to the CI, which would introduce a diff that would need to be committed, I extended the `make fmt` command.
=> feat: add go fmt to make fmt command

third_party/celestia-app/shares/compact_shares_test.go, third_party/celestia-app/shares/parse_compact_shares.go, third_party/celestia-app/shares/range.go, third_party/celestia-app/shares/share_builder.go, third_party/celestia-app/shares/shares.go, third_party/celestia-app/shares/split_compact_shares.go, third_party/celestia-app/shares/utils.go, third_party/celestia-app/testfactory/txs.go, types/tx.go, types/tx_test.go
Adds ability to:
- Convert `TxWithISRs` to Shares
- Convert Shares to byte array (that will be posted on celestia)
- Convert above byte array back to Shares
- Convert Shares back to `TxWithISRs`
- Parse Out of Context Shares
Adds relevant roundtrip tests
Resolves #881 
Resolves #934 
Resolves #886 
Resolves #925 
Note: All shares are written and interpreted as compact shares so they contain reserved bytes (see https://celestiaorg.github.io/celestia-app/specs/data_structures.html#compact-share)
Related PR in `celestia-app`: https://github.com/celestiaorg/celestia-app/pull/1770
=> feat: Txs To Shares Roundtrip

node/full.go, node/full_node_integration_test.go
=> Remove unused fields in full node

types/signed_header.go, types/signed_header_test.go, types/test_utils.go
=> Decouple TestVerify into TestValidateBasic and TestVerify

node/full_node_test.go
=> Refactor full node test

.github/workflows/ci_release.yml
This PR updates the release CI to trigger when a PR with the `create-release` label is merged. 
See tested action: https://github.com/MSevey/workflows/actions/runs/6489995567
=> feat: add release trigger for merged PRs with create-release label

.github/workflows/ci_release.yml, cmd/rollkit/commands/run_node.go
As a precursor to pushing `rollkit start` to more users, I'm adding multiple os testing to the cli ci testing.
Additionally, I extended the CI mode for `rollkit start` so that it runs for 5s, verifies it is still running, and then checks the error on stop to have better coverage.
NOTE: This will require an update to the branch protection rules for the updated CI names.
=> feat(ci): add running the cli on all supported os

da/da_test.go, rpc/json/helpers_test.go, test/server/server.go
The test server start functions have been moved to a separate server package in tests. Mock RPC server is now started directly in rpc/json package.
Resolves #1642
=> test: refactor startup of RPC servers

.github/dependabot.yml
This PR adds updates to the dependabot config to address the PR spam. 
We want to be pulling in rollkit dependency updates ASAP so dependabot should trigger daily, however we care less about the frequency of updates from other dependencies. 
This PR splits our a daily and weekly update for the github actions and gomod triggers. For rollkit owned dependencies, the trigger will remain daily and both minor and patch updates will be grouped. 
For non-rollkit updates, the trigger is reduced to weekly. 
The wildcard dependency strings are based off of [this commit](https://github.com/rollkit/rollkit/commit/d3859461daa9fb7a51abe9d4363cf1ba08efa91d) and [this commit](https://github.com/rollkit/rollkit/commit/562c79e3b498e09811a76b0db8c2bc33b0853314).
Dependabot docs REF: …
=> chore(ci): split rollkit org deps out to reduce spam

specs/lazy-adr/adr-010-remote-signer.md
This PR pulled out the ADR for remote signing from the implementation making it easier for the reviewer by shrinking the scope
=> docs: add ADR for remote signing

pkg/signer/file/file_signer_test.go, pkg/signer/file/local.go
this pr adds a test case and a fix that was zeroing out the internal decoding of ed25519 keys
=> fix: add test case for zero out of priv key

pkg/config/config.go, pkg/config/config_test.go
Ref: https://github.com/rollkit/go-execution-abci/pull/48#discussion_r2044292045
I eventually went with `LoadFromViper`, as the flags are added in the start command and i would have had to duplicate most of the logic otherwise.
`LoadFromViper` should be used for the SDK, as it does some prepossessing of flags. `Load` should be used for any other use case (non SDK based chains).
=> feat: add load from viper

.github/workflows/test.yml, scripts/test.go, scripts/test.mk
This pr adds a go script to run go test for all go.mods 
closes https://github.com/rollkit/rollkit/issues/2181
=> chore: add test script to run tests for all go.mods

pkg/cmd/init.go, rollups/testapp/cmd/init.go, rollups/testapp/cmd/init_test.go, rollups/testapp/main.go
Move init command to `testapp`. Users should use the helpers when creating their init command.
For instance go-abci-execution will have its own init command supporting the SDK genesis.
This was confusing because it wouldn't generate an app state.
=> refactor: move init to testapp

block/aggregation.go, block/manager.go, block/submitter.go, block/sync.go, node/full.go
1. Context cancelled isn't an error, it should be added to multiErr
2. Move cache under `data` instead of `config`
=> refactor: clean-up logs + save cache under data

execution/evm/execution.go, test/e2e/evm_sequencer_e2e_test.go
Add sequencer restart/recovery E2E test which is test 2 in https://github.com/rollkit/rollkit/issues/2351 and revert ExecuteTxs to use previous block hash
=> test: Add sequencer restart/recovery test and revert ExecuteTxs to use previous block hash

block/manager.go, block/submitter.go, pkg/cmd/run_node.go
After https://github.com/evstack/ev-node/pull/2416/ was merged, the logging in evolve node included logs from the headerSyncService's p2p module, store module, and sync module via the go-header library. This caused a lot of noise in evolve node logs and shouldn't be enabled by default.
Also, made the `creating empty block` log back to INFO level so a user can see that evolve node is producing blocks when during no user activity and see what block height the node is at.
Also, fixes formatting issues with DA submission log.
https://www.loom.com/share/42b4be68bee74608b62cfdf07324a829?sid=4f889192-639b-477e-b5c6-fe941d6c7f70
Previously logging looked like this:
Logging now looks like this:
=> fix: Modify Evolve node logging to remove noise

README.md
=> chore: replace rollkit in readme

.github/workflows/docs_build.yml, .github/workflows/docs_deploy.yml, .github/workflows/docs_preview.yml, docs/CLAUDE.md, docs/README.md
=> fix: docs deployment

block/sync.go
We validate after during execution, but before during syncing, but the signature verifier provided by ev-abci needs some data that is saved after applying.
=> fix(block): validate block after applying instead of before during sync

apps/evm/single/cmd/init.go, apps/grpc/single/cmd/init.go, apps/testapp/cmd/init.go, apps/testapp/cmd/init_test.go, docs/guides/da/visualizer.md, docs/guides/reset-state.md, docs/learn/config.md, pkg/config/yaml.go
Point to the correct config name,.
=> chore: correct config name

apps/evm/single/cmd/run.go, apps/grpc/single/cmd/run.go, apps/testapp/cmd/run.go, block/internal/submitting/da_submitter.go, block/internal/submitting/da_submitter_mocks_test.go, block/internal/syncing/da_retriever.go, block/internal/syncing/da_retriever_test.go, core/da/namespace.go, core/da/namespace_test.go, da/jsonrpc/client.go, da/jsonrpc/proxy_test.go, node/helpers_test.go, pkg/config/config.go, pkg/rpc/server/server.go, types/da.go, types/da_test.go
Remove `PrepareNamespace`.
The caller must know what the namespace is: s it bytes? Or is it a string.
If we are using `PrepareNamespace`, we are losing this information, so strings of 29 characters will trigger the wrong path and do not pass validation.
=> refactor(core)!: remove `PrepareNamespace`

block/internal/syncing/da_retriever.go, types/da.go, types/da_test.go
Downloading many blobs would timeout after 10s. We should timeout per request and for all requests.
=> fix(types): add timeout per request in retrieve helper

apps/evm/single/README.md, apps/evm/single/cmd/run.go, apps/grpc/single/cmd/run.go, apps/testapp/cmd/run.go, block/internal/syncing/syncer.go, block/internal/syncing/syncer_backoff_test.go, block/internal/syncing/syncer_benchmark_test.go, block/internal/syncing/syncer_test.go, docs/guides/create-genesis.md, docs/guides/da/celestia-da.md, docs/learn/config.md, pkg/cmd/run_node_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/genesis/genesis.go
UX improvement to move da height from user config to developer config.
The flow is as follow:
The developer once starting is sequencer is able to query its node to get the da start height
They should add it in the genesis they share with the others node operators.
Nodes will fetch directly from the correct DA height.
=> refactor(pkg/config)!: move da start height to genesis

docs/learn/config.md, tools/da-debug/README.md
=> chore: fix markdown lint

Makefile, tools/blob-decoder/README.md, tools/cache-analyzer/README.md, tools/da-debug/README.md, tools/tools.mk
=> chore: add makefile for tools
